int sumaVector(int* array,int cantidad);
float promedioVector(int* array,int cantidad);
int inicializarArray(int* pArray,int cantidad,int valor);
int buscarEspacioLibre(int* pArray,int cantidad);
int isEmptyArray(int* pArray,int cantidad,int valor);
int mostrarUnElemento(int array);
int mostrarArrayElemento(int array[],int cantidad);
int cargaArray(int* pArray,int cantidad);
int vectorMaximo(int* array,int cantidad,int* max);
int vectorMinimo(int* array,int cantidad,int* min);
int CargaVectorParalelo(int*,int*,int*,int*,float*,char*,int);
int mostrarArrayParalelo(int* legajo,int* edad,int* nota1,int* nota2,float* promedio,char* sexo,int cantidad);
int bubbleSort(int* array,int cantidad);
